const WORDS_A1 = [
 { en: "When", uk: "Коли" },
  { en: "Mary", uk: "Мері" },
  { en: "Lennox", uk: "Леннокс" },
  { en: "was", uk: "була" },
  { en: "sent", uk: "відправлена" },
  { en: "to", uk: "до" },
  { en: "Misselthwaite", uk: "Місселтвейт" },
  { en: "Manor", uk: "маєток" },
  { en: "live", uk: "жити" },
  { en: "with", uk: "з" },
  { en: "her", uk: "її" },
  { en: "uncle", uk: "дядьком" },
  { en: "everybody", uk: "усі" },
  { en: "said", uk: "казали" },
  { en: "most", uk: "найбільш" },
  { en: "disagreeable-looking", uk: "неприємної-зовнішності" },
  { en: "seen", uk: "бачена" },
  { en: "It", uk: "Це" },
  { en: "true", uk: "правда" },
  { en: "too", uk: "також" },
  { en: "body", uk: "тіло" },
  { en: "thin", uk: "рідке" },
  { en: "light", uk: "світле" },
  { en: "sour", uk: "кисле" },
  { en: "expression", uk: "вираз" },
  { en: "hair", uk: "волосся" },
  { en: "face", uk: "обличчя" },
  { en: "yellow", uk: "жовте" },
  { en: "India", uk: "Індії" },
  { en: "or", uk: "або" },
  { en: "another", uk: "інший" },
  { en: "Her", uk: "Її" },
  { en: "father", uk: "батько" },
  { en: "held", uk: "обіймав" },
  { en: "position", uk: "посаду" },
  { en: "under", uk: "під" },
  { en: "Government", uk: "урядом" },
  { en: "busy", uk: "зайнятий" },
  { en: "ill", uk: "хворий" },
  { en: "himself", uk: "сам" },
  { en: "mother", uk: "мати" },
  { en: "been", uk: "була" },
  { en: "great", uk: "велика" },
  { en: "beauty", uk: "красуня" },
  { en: "cared", uk: "дбала" },
  { en: "only", uk: "лише" },
  { en: "go", uk: "ходити" },
  { en: "parties", uk: "вечірки" },
  { en: "amuse", uk: "розважати" },
  { en: "herself", uk: "себе" },
  { en: "gay", uk: "веселими" },
  { en: "people", uk: "людьми" },
  { en: "wanted", uk: "мати" },
  { en: "girl", uk: "дитину" },
  { en: "born", uk: "була" },
  { en: "handed", uk: "передали" },
  { en: "over", uk: "на" },
  { en: "care", uk: "няню" },
  { en: "an", uk: "Айя" },
  { en: "made", uk: "змушена" },
  { en: "understand", uk: "зрозуміти" },
  { en: "wished", uk: "бажала" },
  { en: "please", uk: "угодити" },
  { en: "must", uk: "повинна" },
  { en: "keep", uk: "тримати" },
  { en: "child", uk: "подалі" },
  { en: "sight", uk: "погляду" },
  { en: "possible", uk: "можливо" },
  { en: "ugly", uk: "потворною" },
  { en: "baby", uk: "дитиною" },
  { en: "became", uk: "стала" },
  { en: "sickly", uk: "хворобливою" },
  { en: "fretful", uk: "капризною" },
  { en: "toddling", uk: "маленькою" },
  { en: "thing", uk: "дитиною" },
  { en: "kept", uk: "подалі" },
  { en: "out", uk: "назовні" },
  { en: "She", uk: "Вона" },
  { en: "remembered", uk: "не пам’ятала" },
  { en: "seeing", uk: "бачити" },
  { en: "familiarly", uk: "звично" },
  { en: "anything", uk: "нічого" },
  { en: "but", uk: "крім" },
  { en: "dark", uk: "темних" },
  { en: "faces", uk: "облич" },
  { en: "of", uk: "Айя" },
  { en: "Ayah", uk: "інших" },
  { en: "native", uk: "місцеві" },
  { en: "servants", uk: "служниці" },
  { en: "obeyed", uk: "підкорялися" },
  { en: "own", uk: "свою" },
  { en: "way", uk: "волю" },
  { en: "everything", uk: "всьому" },
  { en: "because", uk: "бо" },
  { en: "Mem", uk: "Сахіб" },
  { en: "Sahib", uk: "сердилася" },
  { en: "be", uk: "зла" },
  { en: "angry", uk: "сердита" },
  { en: "disturbed", uk: "спокій" },
  { en: "crying", uk: "плач" },
  { en: "by", uk: "через" },
  { en: "six", uk: "шість" },
  { en: "years", uk: "років" },
  { en: "old", uk: "старою" },
  { en: "tyrannical", uk: "тиранська" },
  { en: "selfish", uk: "егоїстична" },
  { en: "little", uk: "маленька" },
  { en: "pig", uk: "свинка" },
  { en: "as", uk: "як" },
  { en: "ever", uk: "коли-небудь" },
  { en: "lived", uk: "жила" },
  { en: "The", uk: "Молода" },
  { en: "young", uk: "молода" },
  { en: "English", uk: "англійська" },
  { en: "governess", uk: "гувернантка" },
  { en: "who", uk: "яка" },
  { en: "teach", uk: "навчити" },
  { en: "write", uk: "писати" },
  { en: "disliked", uk: "не любила" },
  { en: "so", uk: "так" },
  { en: "much", uk: "дуже" },
  { en: "that", uk: "що" },
  { en: "gave", uk: "покинула" },
  { en: "up", uk: "роботу" },
  { en: "place", uk: "місце" },
  { en: "three", uk: "три" },
  { en: "months", uk: "місяці" },
  { en: "and", uk: "і" },
  { en: "when", uk: "коли" },
  { en: "other", uk: "інші" },
  { en: "governesses", uk: "гувернантки" },
  { en: "came", uk: "приходили" },
  { en: "try", uk: "спробувати" },
  { en: "fill", uk: "заповнити" },
  { en: "it", uk: "її" },
  { en: "they", uk: "вони" },
  { en: "always", uk: "завжди" },
  { en: "went", uk: "йшли" },
  { en: "away", uk: "геть" },
  { en: "in", uk: "у" },
  { en: "a", uk: "коротший" },
  { en: "shorter", uk: "коротший" },
  { en: "time", uk: "час" },
  { en: "than", uk: "ніж" },
  { en: "the", uk: "перший" },
  { en: "first", uk: "перший" },
  { en: "one", uk: "один" },
  { en: "So", uk: "Отже" },
  { en: "if", uk: "якби" },
  { en: "had", uk: "мала" },
  { en: "not", uk: "не" },
  { en: "chosen", uk: "обрала" },
  { en: "really", uk: "справді" },
  { en: "want", uk: "хотіла" },
  { en: "know", uk: "знати" },
  { en: "how", uk: "як" },
  { en: "read", uk: "читати" },
  { en: "books", uk: "книги" },
  { en: "she", uk: "вона" },
  { en: "would", uk: "б не" },
  { en: "never", uk: "ніколи" },
  { en: "have", uk: "не" },
  { en: "learned", uk: "вивчила" },
  { en: "letters", uk: "літери" },
  { en: "at", uk: "у" },
  { en: "all", uk: "взагалі" }
];














