const WORDS_A1 = [
    { en: "a", uk: "один" },
  { en: "aback", uk: "назад" },
  { en: "abed", uk: "у ліжку" },
  { en: "abhor", uk: "ненавидіти" },
  { en: "abide", uk: "дотримуватися" },
  { en: "able", uk: "здатний" },
  { en: "aboard", uk: "на борту" },
  { en: "about", uk: "про" },
  { en: "above", uk: "над" },
  { en: "abroad", uk: "за кордоном" },
  { en: "absence", uk: "відсутність" },
  { en: "absent", uk: "відсутній" },
  { en: "absolute", uk: "абсолютний" },
  { en: "absolutely", uk: "абсолютно" },
  { en: "absorb", uk: "поглинати" },
  { en: "abstract", uk: "абстрактний" },
  { en: "absurd", uk: "абсурдний" },
  { en: "abundance", uk: "достаток" },
  { en: "abundant", uk: "рясний" },
  { en: "abuse", uk: "зловживання" },
  { en: "academic", uk: "академічний" },
  { en: "academy", uk: "академія" },
  { en: "accelerate", uk: "прискорювати" },
  { en: "accent", uk: "акцент" },
  { en: "accept", uk: "приймати" },
  { en: "acceptable", uk: "прийнятний" },
  { en: "acceptance", uk: "прийняття" },
  { en: "access", uk: "доступ" },
  { en: "accessible", uk: "доступний" },
  { en: "accident", uk: "випадок" },
  { en: "accompany", uk: "супроводжувати" },
  { en: "accomplish", uk: "здійснити" },
  { en: "according", uk: "згідно" },
  { en: "account", uk: "рахунок" },
  { en: "accurate", uk: "точний" },
  { en: "accuse", uk: "звинувачувати" },
  { en: "accustomed", uk: "звичний" },
  { en: "ache", uk: "біль" },
  { en: "achieve", uk: "досягати" },
  { en: "achievement", uk: "досягнення" },
  { en: "acid", uk: "кислота" },
  { en: "acknowledge", uk: "визнавати" },
  { en: "acquaintance", uk: "знайомство" },
  { en: "acquire", uk: "здобувати" },
  { en: "acquisition", uk: "придбання" },
  { en: "acquit", uk: "виправдати" },
  { en: "across", uk: "крізь" },
  { en: "act", uk: "діяти" },
  { en: "action", uk: "дія" },
  { en: "active", uk: "активний" },
  { en: "activity", uk: "активність" },
  { en: "actor", uk: "актор" },
  { en: "actress", uk: "акторка" },
  { en: "actual", uk: "справжній" },
  { en: "actually", uk: "насправді" },
  { en: "acute", uk: "гострий" },
  { en: "adapt", uk: "пристосовувати" },
  { en: "add", uk: "додавати" },
  { en: "addition", uk: "додавання" },
  { en: "additional", uk: "додатковий" },
  { en: "address", uk: "адреса" },
  { en: "adequate", uk: "адекватний" },
  { en: "adjust", uk: "налаштовувати" },
  { en: "admire", uk: "захоплюватися" },
  { en: "admission", uk: "вступ" },
  { en: "admit", uk: "визнавати" },
  { en: "adopt", uk: "усиновлювати" },
  { en: "adorable", uk: "чарівний" },
  { en: "adore", uk: "обожнювати" },
  { en: "adult", uk: "дорослий" },
  { en: "advance", uk: "просуватися" },
  { en: "advanced", uk: "передовий" },
  { en: "advantage", uk: "перевага" },
  { en: "adventure", uk: "пригода" },
  { en: "adverb", uk: "прислівник" },
  { en: "adversary", uk: "супротивник" },
  { en: "adverse", uk: "несприятливий" },
  { en: "advertise", uk: "рекламувати" },
  { en: "advertisement", uk: "реклама" },
  { en: "advice", uk: "порада" },
  { en: "advise", uk: "радити" },
  { en: "adviser", uk: "радник" },
  { en: "advocate", uk: "захисник" },
  { en: "aesthetic", uk: "естетичний" },
  { en: "afar", uk: "здалеку" },
  { en: "affair", uk: "справа" },
  { en: "affect", uk: "впливати" },
  { en: "affection", uk: "прихильність" },
  { en: "affiliate", uk: "філія" },
  { en: "affirm", uk: "стверджувати" },
  { en: "afford", uk: "дозволити собі" },
  { en: "afraid", uk: "наляканий" },
  { en: "after", uk: "після" },
  { en: "afternoon", uk: "пополудні" },
  { en: "afterward", uk: "згодом" },
  { en: "again", uk: "знову" },
  { en: "against", uk: "проти" },
  { en: "age", uk: "вік" },
  { en: "agency", uk: "агентство" },
  { en: "agent", uk: "агент" },
  { en: "aggressive", uk: "агресивний" },
  { en: "ago", uk: "тому" },
  { en: "agree", uk: "погоджуватися" },
];














